### ISSUE TITLE
Workflows 

### ISSUE THREAD

**Issue by aavanesy** [r-dbi/docker#5]
Tracking logs of workflow modifications

**Comment by aavanesy** [comment]
@krlmlr please remove within the packages
Package `rdb` https://github.com/krlmlr/rdb/pkgs/container/rdb
Package `r_mssql` https://github.com/krlmlr/rdb/pkgs/container/rdb%2Fr_mssql
These are no longer necessary

**Comment by krlmlr** [comment]
Done. Can this be closed now?
